### ISSUE TITLE
do all folders+files HAVE to be chmod777?

### ISSUE THREAD

**Issue by absoluto** [sitecake/sitecake#56]
do all folders+files HAVE to be chmod777?

cheers, michael

**Comment by sitecake** [comment]
Sitecake needs to be able to create folders in the site root folder and to be able to manipulate files in them (`files`, `images`, `sitecake`, `sitecake-temp` and `sitecake-backup`). Also, Sitecake needs to modify HTML page files.
One way to achieve this is to have all these files/folders writable for the PHP process (e.g. chmod 777). If that's not possible because of the PHP/configuration setup. An alternative way is to configure Sitecake to use FTP to modify files. Please check `sitecake/<version>/server/config.php`.
